yarnPath: ".yarn/releases/yarn-4.9.1.cjs"

nodeLinker: node-modules

enableGlobalCache: true

npmRegistryServer: "https://registry.yarnpkg.com"

checksumBehavior: update

enableStrictSsl: true

# Optional: Enables detailed output for debugging
logFilters:
  - code: YN0013
    level: discard
  - code: YN0061
    level: discard
